( // this code was autogenerated from PJS
(function($p) {
    var FrameRateLibrary = (function() {
        function FrameRateLibrary() {
            var $this_1 = this;

            function $superCstr() {
                $p.extendClassChain($this_1)
            }
            $this_1.parent = null;

            function draw$0() {
                var rate = $this_1.parent.__frameRate;
                $this_1.parent.fill(0);
                $this_1.parent.rectMode($p.CORNER);
                $this_1.parent.rect(0, 3, 50, 20);
                $this_1.parent.fill(255);
                $this_1.parent.text($this_1.parent.nf(rate, 0, 2) + " fps", 0, 20);
            }
            $p.addMethod($this_1, 'draw', draw$0);

            function $constr_1(parent) {
                $superCstr();

                $this_1.parent = parent;
                parent.registerDraw($this_1.$self);
            }

            function $constr() {
                if (arguments.length === 1) {
                    $constr_1.apply($this_1, arguments);
                } else $superCstr();
            }
            $constr.apply(null, arguments);
        }
        return FrameRateLibrary;
    })();
    $p.FrameRateLibrary = FrameRateLibrary;

})(Processing.prototype));
